// Browser behavior, not source matching: keep reader controls usable by keyboard.
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
const runtime = process.env.PLAYWRIGHT_PATH;
const { chromium }: typeof import('playwright') = await import(runtime ? `${runtime.replace(/\/$/, '')}/index.mjs` : 'playwright');
const browser = await chromium.launch(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {});
const base = (process.env.BOOK_BASE_URL || 'http://127.0.0.1:8766/rust-game-hacking-book/').replace(/\/?$/, '/');
const output = process.env.READER_SCREENSHOTS;
if (output) await mkdir(output, { recursive: true });
let keys = 0;
const cases = [];
try {
  for (const width of [420, 1280]) {
    for (const lesson of ['1/05', '10/02']) {
      const context = await browser.newContext({ viewport: { width, height: 1000 } });
      await context.route('**/*', route => new URL(route.request().url()).origin === new URL(base).origin ? route.continue() : route.abort());
      const page = await context.newPage(), errors: string[] = [];
      page.on('pageerror', error => errors.push(error.message));
      await page.goto(base + 'pages/' + lesson + '/', { waitUntil: 'domcontentloaded' });
      await page.waitForFunction(() => document.querySelector<HTMLElement>('[data-lesson-notes]')?.dataset.noteReady === 'true');
      const press = async (key: string) => { await page.keyboard.press(key); keys++; };
      const area = page.locator('[data-note-text]'), panel = page.locator('.lesson-notes__panel');
      const sidebarBefore = await page.evaluate(() => document.documentElement.dataset.academySidebar || 'shown');
      await press('Alt+n');
      assert.equal(await panel.isVisible(), true);
      assert.equal(await area.evaluate(node => node === document.activeElement), true);
      assert.equal(await page.evaluate(() => document.documentElement.dataset.academySidebar || 'shown'), sidebarBefore, 'Notes shortcut leaves the lesson list alone');
      await area.fill('# A saved note\n\nFollow the value through a function.');
      await area.dispatchEvent('input');
      await page.waitForFunction(() => JSON.parse(localStorage.getItem('gha-note:' + document.querySelector<HTMLElement>('[data-lesson-notes]')?.dataset.noteId) || 'null')?.text.includes('A saved note'));
      await press('Shift+Tab');
      assert.equal(await page.evaluate(() => (document.activeElement as HTMLElement | null)?.dataset.noteTab), 'write');
      await press('ArrowRight');
      const selected = page.locator('[data-note-tab][aria-selected="true"]');
      assert.equal(await selected.getAttribute('data-note-tab'), 'preview');
      assert.equal(await selected.evaluate(node => node === document.activeElement), true);
      assert.equal(await page.locator('[data-note-tab][tabindex="0"]').count(), 1);
      assert.equal(await panel.locator('[role="tabpanel"]:visible').count(), 1);
      const preview = page.locator('[data-note-preview]');
      assert.equal(await selected.getAttribute('aria-controls'), await preview.getAttribute('id'));
      assert.equal(await preview.getAttribute('aria-labelledby'), await selected.getAttribute('id'));
      assert.match(await preview.innerText(), /Follow the value/);
      await press('Tab');
      assert.equal(await preview.evaluate(node => node === document.activeElement), true);
      await press('Escape');
      assert.equal(await panel.isVisible(), false);
      assert.equal(await page.locator('[data-note-open]').evaluate(node => node === document.activeElement), true);
      await press('Alt+n');
      assert.equal(await preview.evaluate(node => node === document.activeElement), true, 'Reopening Preview focuses its visible panel');
      await press('Shift+Tab');
      await press('Home');
      assert.equal(await selected.getAttribute('data-note-tab'), 'write');
      await press('End');
      assert.equal(await selected.getAttribute('data-note-tab'), 'preview');
      await press('ArrowRight');
      assert.equal(await selected.getAttribute('data-note-tab'), 'write', 'Tabs wrap');
      await press('ArrowLeft');
      assert.equal(await selected.getAttribute('data-note-tab'), 'preview');
      if (output) await page.screenshot({ path: `${output}/notes-${lesson.replace('/', '-')}-${width}.png` });
      await press('Alt+n');
      assert.equal(await panel.isVisible(), false);
      await page.locator('[data-note-open]').evaluate(node => node.blur());
      await press('Alt+b');
      assert.equal(await page.evaluate(() => document.documentElement.dataset.academySidebar), 'hidden');
      assert.equal(await panel.isVisible(), false, 'Lesson-list shortcut leaves Notes closed');
      await press('Alt+b');
      assert.equal(await page.evaluate(() => document.documentElement.dataset.academySidebar), 'shown');
      if (lesson === '1/05') {
        const root = page.locator('[data-speedtype][data-speedtype-recall]').first();
        const recall = JSON.parse(await root.getAttribute('data-speedtype-recall') ?? '[]') as { text: string }[];
        const start = root.getByRole('button', { name: 'Copy visible code', exact: true });
        await start.focus(); await press('Enter');
        const readable = root.locator('[data-speedtype-readable]');
        const input = root.locator('.kit-speedtype__input');
        assert.equal(await input.getAttribute('aria-describedby'), await readable.getAttribute('id'));
        assert.notEqual(await readable.getAttribute('aria-hidden'), 'true');
        assert.equal((await readable.textContent() ?? '').trim(), (await root.locator('.kit-speedtype__code code').textContent() ?? '').trim());
        if (output) await page.screenshot({ path: `${output}/copy-${width}.png` });
        await press('Escape');
        assert.equal(await start.evaluate(node => node === document.activeElement), true);
        const recallStart = root.locator('[data-speedtype-start="recall"]');
        await recallStart.focus(); await press('Enter');
        const masked = await readable.textContent();
        assert.ok(masked);
        assert.match(masked, /_/);
        assert.ok(await root.locator('[data-recall-hidden]').count() > 0, 'Sparse recall has genuine short blanks');
        assert.equal((await readable.textContent() ?? '').trim(), (await root.locator('.kit-speedtype__code code').textContent() ?? '').trim());
        const reveal = root.getByRole('button', { name: 'Show hidden code', exact: true });
        await reveal.focus(); await press('Space');
        for (const fragment of recall) assert.ok((await readable.textContent() ?? '').includes(fragment.text), 'Deliberate reveal updates the reading copy');
        assert.match(await root.locator('.kit-speedtype__mode').innerText(), /Assisted/);
        const hide = root.getByRole('button', { name: 'Hide answers', exact: true });
        await hide.focus(); await press('Space');
        assert.equal(await readable.textContent(), masked);
        if (output) await page.screenshot({ path: `${output}/recall-${width}.png` });
        await press('Escape');
        assert.equal(await recallStart.evaluate(node => node === document.activeElement), true);
      }
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1), false);
      assert.deepEqual(errors, []);
      cases.push({ width, lesson, errors });
      await context.close();
    }
  }
} finally { await browser.close(); }
if (output) await writeFile(`${output}/results.json`, JSON.stringify({ cases, keys }, null, 2));
console.log(`reader-keyboard: ${cases.length} page/width groups, ${keys} actual key actions; tabs, saved notes, independent shortcuts and masked reading copies pass.`);
