import assert from 'node:assert/strict';
import type { Locator } from 'playwright';
const requireText = (text: string | null): string => { assert.notEqual(text, null, 'Expected page text exists'); return text!; };
import { mkdirSync } from 'node:fs';
const runtime = process.env.PLAYWRIGHT_PATH;
const { chromium }: typeof import('playwright') = await import(runtime ? `${runtime.replace(/\/$/, '')}/index.mjs` : 'playwright');
const browser = await chromium.launch(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {});
const base = (process.env.BOOK_BASE_URL || 'http://127.0.0.1:8766/rust-game-hacking-book/').replace(/\/?$/, '/');
const output = process.env.QA_OUTPUT;
if (output) mkdirSync(output, { recursive: true });
let clicks = 0, cases = 0;
try {
  for (const width of [420, 1280]) {
    const context = await browser.newContext({ viewport: { width, height: 1000 }, reducedMotion: 'reduce' });
    await context.route('https://**/*', route => new URL(route.request().url()).origin === new URL(base).origin ? route.continue() : route.abort());
    const page = await context.newPage(), errors: string[] = [];
    page.setDefaultTimeout(10000); page.on('pageerror', e => errors.push(e.message));
    const clean = async () => { assert.deepEqual(errors, []); assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1), false); };
    const shot = async (root: Locator, name: string) => { await root.scrollIntoViewIfNeeded(); await page.evaluate(() => document.fonts.ready); if (output) await root.screenshot({ path: `${output}/${name}-${width}.png` }); await clean(); };
    const click = async (locator: Locator) => { await locator.click(); clicks++; };
    const input = async (locator: Locator, value: string | number) => locator.evaluate((node: HTMLInputElement, value) => { node.value = String(value); node.dispatchEvent(new Event('input', { bubbles: true })); }, value);
    const picture = (root: Locator) => root.locator('svg [data-a]').evaluateAll(nodes => nodes.map(node => [node.dataset.a, node.getAttribute('transform'), node.getAttribute('opacity') || '1', node.dataset.role || 'plain', node.textContent]));
    await page.goto(base + 'pages/4/06/', { waitUntil: 'domcontentloaded' });
    const bfs = page.locator('[data-scene-id="scene-bfs-around-wall"]');
    await bfs.locator('[data-scene-explore]').waitFor({ state: 'visible' });
    const original = await bfs.locator('svg').innerHTML();
    const originalPicture = await picture(bfs);
    await shot(bfs, 'bfs-default');
    await bfs.locator('[data-scene-input="wall10"]').uncheck(); clicks++;
    assert.match(requireText(await bfs.locator('[data-scene-result]').textContent()), /shortest route needs 2 moves/);
    assert.notEqual(await bfs.locator('svg').innerHTML(), original);
    assert.match(requireText(await bfs.locator('.scene__steps').textContent()), /2 moves/);
    await shot(bfs, 'bfs-clear'); cases++;
    await bfs.locator('[data-scene-input="wall10"]').check(); clicks++;
    await bfs.locator('[data-scene-input="wall01"]').check(); clicks++;
    assert.match(requireText(await bfs.locator('[data-scene-result]').textContent()), /No route.*queue.*empty/s);
    assert.match(requireText(await bfs.locator('[data-a="route"]').textContent()), /none/);
    await shot(bfs, 'bfs-blocked'); cases++;
    await click(bfs.locator('[data-scene-reset]'));
    assert.deepEqual(await picture(bfs), originalPicture, 'Reset restores authored actor positions, visibility, roles and labels');
    assert.match(requireText(await bfs.locator('[data-scene-result]').textContent()), /4 moves/);

    await page.goto(base + 'pages/5/09/', { waitUntil: 'domcontentloaded' });
    const camera = page.locator('[data-scene-id="scene-world-to-screen"]');
    await camera.locator('[data-scene-explore]').waitFor({ state: 'visible' });
    const cameraOriginal = await camera.locator('svg').innerHTML();
    const cameraPicture = await picture(camera);
    await shot(camera, 'camera-default');
    await input(camera.locator('[data-scene-input="cameraX"]'), 2);
    assert.match(requireText(await camera.locator('[data-scene-result]').textContent()), /Nearer marker: \(400,300\).*Farther marker: \(400,350\)/);
    assert.notEqual(await camera.locator('svg').innerHTML(), cameraOriginal); cases++;
    await input(camera.locator('[data-scene-input="depth"]'), 0.5);
    assert.match(requireText(await camera.locator('[data-scene-result]').textContent()), /Nearer point: clipped/); cases++;
    await input(camera.locator('[data-scene-input="depth"]'), 6);
    assert.match(requireText(await camera.locator('[data-scene-result]').textContent()), /Farther point: clipped by Z/);
    assert.equal(await camera.locator('[data-a="marker"]').getAttribute('opacity'), '0', 'clipped marker is hidden');
    await shot(camera, 'camera-clipped'); cases++;
    await input(camera.locator('[data-scene-input="fov"]'), 30);
    assert.match(requireText(await camera.locator('[data-scene-output="fov"]').textContent()), /30/); cases++;
    await click(camera.locator('[data-scene-reset]'));
    assert.deepEqual(await picture(camera), cameraPicture);
    // Manual playback still explains the changed computed scene.
    await input(camera.locator('[data-scene-input="cameraX"]'), 0);
    await click(camera.locator('[data-scene-action="prev"]'));
    assert.equal(await camera.getAttribute('data-playing'), 'false');
    await click(camera.locator('[data-scene-action="next"]'));
    await clean();

    for (const path of ['pages/4/09/', 'pages/4/10/']) {
      await page.goto(base + path, { waitUntil: 'domcontentloaded' });
      const tree = page.locator('[data-sim-lab="behavior-tree"]');
      await tree.locator('.sim-lab__tree-node').first().waitFor();
      const explanation = tree.locator('.sim-lab__explain');
      assert.match(requireText(await explanation.textContent()), /Chosen action: attack/);
      await shot(tree, `${path.includes('/09/') ? 'tree' : 'tree-second-host'}-default`);
      await click(tree.locator('[data-tree-node-id="health"] > button'));
      assert.equal(await tree.locator('[data-tree-editor]').getAttribute('open'), '');
      await tree.locator('[id$="-tree-limit"]').fill('40');
      await click(tree.locator('[data-tree-edit="update"]'));
      assert.match(requireText(await explanation.textContent()), /Chosen action: flee/); cases++;
      await tree.locator('[id$="-tree-parent"]').selectOption('root');
      await tree.locator('[id$="-tree-child"]').selectOption('flee');
      await click(tree.locator('[data-tree-edit="disconnect"]'));
      assert.match(requireText(await explanation.textContent()), /Chosen action: attack/);
      assert.equal(await tree.locator('.sim-lab__tree [data-tree-node-id="flee"]').count(), 0, 'detached branch leaves connected drawing'); cases++;
      await click(tree.locator('[data-tree-edit="connect"]'));
      for (let i = 0; i < 3; i++) await click(tree.locator('[data-tree-edit="earlier"]'));
      assert.match(requireText(await explanation.textContent()), /Chosen action: flee/); cases++;
      await click(tree.locator('[data-tree-edit="connect"]'));
      assert.match(requireText(await tree.locator('.sim-lab__tree-status').textContent()), /Disconnect/);
      assert.match(requireText(await explanation.textContent()), /Chosen action: flee/); cases++;
      await tree.locator('[id$="-tree-new-kind"]').selectOption('action:patrol');
      await click(tree.locator('[data-tree-edit="add"]'));
      await tree.locator('[id$="-tree-parent"]').selectOption('root');
      await tree.locator('[id$="-tree-child"]').selectOption('edited-1');
      await click(tree.locator('[data-tree-edit="connect"]'));
      assert.equal(await tree.locator('.sim-lab__tree [data-tree-node-id="edited-1"]').count(), 1); cases++;
      await click(tree.locator('[data-tree-edit="disconnect"]'));
      await click(tree.locator('[data-tree-edit="remove"]'));
      assert.equal(await tree.locator('[id$="-tree-node"] option[value="edited-1"]').count(), 0); cases++;
      await shot(tree, `${path.includes('/09/') ? 'tree' : 'tree-second-host'}-edited`);
      await click(tree.getByRole('button', { name: 'Reset', exact: true }));
      assert.match(requireText(await explanation.textContent()), /Chosen action: attack/);
      assert.equal(await tree.locator('.sim-lab__tree-node').count(), 15);
      await click(tree.getByRole('button', { name: 'Clear trace', exact: true }));
      assert.equal(await tree.locator('.sim-lab__execution').isVisible(), false);
      await click(tree.getByRole('button', { name: 'Run one tick', exact: true }));
      assert.ok(await tree.locator('.sim-lab__execution li').count() > 1);
      await clean();
    }
    await page.goto(base + 'pages/5/07/', { waitUntil: 'domcontentloaded' });
    const formula = page.locator('[data-formula-builder="camera-shake"]');
    await formula.locator('input[type="range"]').first().waitFor();
    await shot(formula, 'shake-default');
    for (const time of [0.5, 1]) {
      await input(formula.getByRole('slider', { name: 'Change the value of time since hit', exact: true }), time);
      assert.match(requireText(await formula.locator('.formula-builder__steps').textContent()), /finished.*0 px/);
      assert.match(requireText(await formula.locator('.formula-builder__explain').textContent()), /offset is 0/); cases++;
    }
    await shot(formula, 'shake-finished');
    await context.close();
  }
  console.log(`simulation-editors: ${cases} changed-result cases, ${clicks} actual clicks, 420/1280px, original resets, no errors or overflow.`);
} finally { await browser.close(); }
