// Generate stable .mjs CLI entries; all authored logic stays in native TypeScript.
import { readFile, writeFile } from 'node:fs/promises';
interface Entry { entry: string; implementation: string }
function record(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value); }
const value: unknown = JSON.parse(await readFile(new URL('./generated-compatibility.json', import.meta.url), 'utf8'));
if (!record(value) || value.version !== 1 || !Array.isArray(value.entries)) throw new Error('Invalid generated compatibility manifest');
const entries: Entry[] = [];
for (const item of value.entries as unknown[]) {
  if (!record(item) || typeof item.entry !== 'string' || typeof item.implementation !== 'string' ||
      !/^[a-z0-9-]+\.mjs$/.test(item.entry) || item.implementation !== item.entry.replace(/\.mjs$/, '.ts')) throw new Error('Unsafe compatibility entry');
  entries.push({ entry: item.entry, implementation: item.implementation });
}
if (new Set(entries.map(item => item.entry)).size !== entries.length) throw new Error('Duplicate compatibility entry');
entries.sort((a, b) => a.entry.localeCompare(b.entry));
const check = process.argv.includes('--check');
for (const item of entries) {
  await readFile(new URL(item.implementation, import.meta.url), 'utf8');
  const source = `// @generated by generate-compat-entries.ts; do not edit.
// Authored logic: ${item.implementation}; native Node26 TypeScript.
export * from './${item.implementation}';
`;
  const file = new URL(item.entry, import.meta.url);
  if (check) {
    if (await readFile(file, 'utf8') !== source) throw new Error(`Outdated generated entry: ${item.entry}`);
  } else await writeFile(file, source);
}
console.log(`compatibility entries: ${entries.length} ${check ? 'verified' : 'generated'}`);
